version: '3.9'
services:
  mysql:
    image: mysql:8.0.34
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: yq20031208
      MYSQL_USER: cuyar
      MYSQL_PASSWORD: yq20031208
    depends_on:
      - mysql-job-dbdata
    ports:
      - "3306:3306"
    volumes:
      - mysql-job-dbdata:/var/lib/mysql


  # 自动加载数据
  mysql-job-dbdata:
    image: alpine:3.18.2
    container_name: mysql-job-dbdata
    volumes:
      - /var/lib/mysql
