server:
  port: 8091

#应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'

#线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        block-queue-size: 5000
        max-pool-size: 50
        keep-alive-time: 5000
        policy: CallerRunsPolicy


# ChatGPT SDK Config
chatgpt:
  sdk:
    config:
      api-host: https://pro-share-aws-api.zcyai.com/
      api-key: sk-1JvI5Ups3Ygt5krh3f4cEeC5292a451d95694c970dFa1fF5


#ChatGLM SDK Config
#chatglm:
#  sdk:
#    config:
#      #官方地址https://open.bigmodel.cn/
#      api-host: https://open.bigmodel.cn/
#      api-secret-key: a391bf252379bc2ed4164e2363e00516.0gJYz4WhwyhboEHC


# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
