server:
  port: 80

#应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'



# ChatGPT SDK Config
chatgpt:
  sdk:
    config:
      api-host: https://pro-share-aws-api.zcyai.com/
      api-key: sk-PbgyE7PeErEvJQz83aCeC28038874dC1BeCaBb07Af9e35C8
      auth-token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4ZmciLCJleHAiOjE2OTAwMzI5MDQsImlhdCI6MTY5MDAyOTMwNCwianRpIjoiOTBkNzc5NjYtOWM5MS00MGVmLWJmNjktNzYzNDljNmUyMDkyIiwidXNlcm5hbWUiOiJ4ZmcifQ.x7P6Rc249SgbxpqWhgKahYP8A8AllNI_26DV08a1AZs


#ChatGLM SDK Config
#chatglm:
#  sdk:
#    config:
#      #官方地址https://open.bigmodel.cn/
#      api-host: https://open.bigmodel.cn/
#      api-secret-key: a391bf252379bc2ed4164e2363e00516.0gJYz4WhwyhboEHC


# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml